version: "3.9"
services:
  baw:
    container_name: client
    build:
      context: ./billing-app-web
    ports:
      - 3000:3000
    volumes:
      - ./billing-app-web:/baw
      - ./billing-app-web/node_modules:/client
    command: npm run start
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  babedb:
    container_name: babedb
    image: postgres:alpine
    ports:
      - 5432:5432
    env_file:
      - ./billing-app-backend--expenditures/src/database/.env
    volumes:
      - ./billing-app-backend--expenditures/src/database/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U billinguser -d billingdb"]
      interval: 5s
      timeout: 5s
      retries: 12

  babe:
    container_name: babe
    build:
      context: ./billing-app-backend--expenditures
    ports:
      - 4000:4000
    volumes:
      - ./src:/babe/src
    environment:
      - POSTGRES_HOST=babedb
      - DATABASE_URL=postgres://billinguser:password@babedb:5432/billingdb
    # command: # The command docker will execute when starting the container, this command is not allowed to exit, if it does your container will stop
    #   - sh
    #   - ./wait-for-it.sh
    #   - --timeout=30
    #   - babedb:5432
    #   - --
    #   # - sh
    #   - -c
    #   - npm run migrate-up && npm run start
    depends_on:
      babedb:
        condition: service_healthy
